//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TilePlayer {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TilePlayer.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        internal static string Buy {
            get {
                return ResourceManager.GetString("Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © {0} Agamura. All rights reserved..
        /// </summary>
        internal static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable disturbing elements.
        /// </summary>
        internal static string DisableDisturbingElements {
            get {
                return ResourceManager.GetString("DisableDisturbingElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable disturbing elements termination.
        /// </summary>
        internal static string DisableDisturbingElementsTemination {
            get {
                return ResourceManager.GetString("DisableDisturbingElementsTemination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disturbing Elements Hiding.
        /// </summary>
        internal static string DisturbingElementsHiding {
            get {
                return ResourceManager.GetString("DisturbingElementsHiding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disturbing Elements Immunity.
        /// </summary>
        internal static string DisturbingElementsImmunity {
            get {
                return ResourceManager.GetString("DisturbingElementsImmunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} left: {1}.
        /// </summary>
        internal static string DisturbingElementsLeft {
            get {
                return ResourceManager.GetString("DisturbingElementsLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functionality not enabled in {0}..
        /// </summary>
        internal static string EditionFunctionalityWarning {
            get {
                return ResourceManager.GetString("EditionFunctionalityWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Do you want to buy TilePlayer {1}?.
        /// </summary>
        internal static string EditionWantToBuy {
            get {
                return ResourceManager.GetString("EditionWantToBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a {0} with limited functionality..
        /// </summary>
        internal static string EditionWarning {
            get {
                return ResourceManager.GetString("EditionWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Edition.
        /// </summary>
        internal static string FullEdition {
            get {
                return ResourceManager.GetString("FullEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your gamertag.
        /// </summary>
        internal static string Gamertag {
            get {
                return ResourceManager.GetString("Gamertag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Scores {0}x{1}.
        /// </summary>
        internal static string HighScoresMatrixSize {
            get {
                return ResourceManager.GetString("HighScoresMatrixSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string IconAbout {
            get {
                return ResourceManager.GetString("IconAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disturbing On/Off.
        /// </summary>
        internal static string IconDisturbingElement {
            get {
                return ResourceManager.GetString("IconDisturbingElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Scores.
        /// </summary>
        internal static string IconHighScores {
            get {
                return ResourceManager.GetString("IconHighScores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size/Numbers.
        /// </summary>
        internal static string IconMatrix {
            get {
                return ResourceManager.GetString("IconMatrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string IconPause {
            get {
                return ResourceManager.GetString("IconPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string IconSettings {
            get {
                return ResourceManager.GetString("IconSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start/Resume.
        /// </summary>
        internal static string IconStart {
            get {
                return ResourceManager.GetString("IconStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string IconStop {
            get {
                return ResourceManager.GetString("IconStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TilePlayer, Agamura, and the Agamura logo are trademarks of Agamura, Inc. All other names are trademarks of their respective owners..
        /// </summary>
        internal static string LegalNotice {
            get {
                return ResourceManager.GetString("LegalNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}x{1}.
        /// </summary>
        internal static string MatrixSize {
            get {
                return ResourceManager.GetString("MatrixSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You were unable to solve the puzzle in a reasonable amount of time. Try again and good luck!.
        /// </summary>
        internal static string MessageGameOver {
            get {
                return ResourceManager.GetString("MessageGameOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moves: {0}.
        /// </summary>
        internal static string Moves {
            get {
                return ResourceManager.GetString("Moves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        internal static string NA {
            get {
                return ResourceManager.GetString("NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to publish your score of {0}?.
        /// </summary>
        internal static string PublishScore {
            get {
                return ResourceManager.GetString("PublishScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score: {0}.
        /// </summary>
        internal static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scorpion.
        /// </summary>
        internal static string Scorpion {
            get {
                return ResourceManager.GetString("Scorpion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scorpions.
        /// </summary>
        internal static string Scorpions {
            get {
                return ResourceManager.GetString("Scorpions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show tile numbers.
        /// </summary>
        internal static string ShowTileNumbers {
            get {
                return ResourceManager.GetString("ShowTileNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up for TilePlayer.
        /// </summary>
        internal static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Over!.
        /// </summary>
        internal static string StatusGameOver {
            get {
                return ResourceManager.GetString("StatusGameOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused: Shake or press play to resume.
        /// </summary>
        internal static string StatusPaused {
            get {
                return ResourceManager.GetString("StatusPaused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready: Shake or press play to start.
        /// </summary>
        internal static string StatusReady {
            get {
                return ResourceManager.GetString("StatusReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running: Slide the tiles to solve the puzzle.
        /// </summary>
        internal static string StatusRunning {
            get {
                return ResourceManager.GetString("StatusRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solved!.
        /// </summary>
        internal static string StatusSolved {
            get {
                return ResourceManager.GetString("StatusSolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile Numbers.
        /// </summary>
        internal static string TileNumbers {
            get {
                return ResourceManager.GetString("TileNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial Edition.
        /// </summary>
        internal static string TrialEdition {
            get {
                return ResourceManager.GetString("TrialEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning!.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome {0}!.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
